name: intl_phone_field
description: A customised Flutter TextFormField to input international phone number along with country code.
version: 3.3.0
homepage: https://github.com/vanshg395/intl_phone_field

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
    git:
      url: https://github.com/loksoon/font
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.12


flutter:
  assets:
    - assets/flags/
